### ISSUE TITLE
[ENH] Default configuration for datasets statistics (common reports)

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#297]
**Is your feature request related to a problem? Please describe.**

At the moment, if we want to enable common reports for a given study/dataset, we need to provide a substantial configuration similar to the following:

```yaml
common_report:
  enabled: True
  effect_groups:
  - LGDs
  - nonsynonymous
  - UTRs

  effect_types:
  - Nonsense
  - Frame-shift
  - Splice-site
  - Missense
  - No-frame-shift
  - noStart
  - noEnd
  - Synonymous
  - Non coding
  - Intron
  - Intergenic
  - "3'-UTR"
  - "5'-UTR"
```  

**Describe the solution you'd like**
I want to have default values for `effect_groups` and `effect_types,` and if somebody wants to enable `common_report` the configuration could be reduced to:

```yaml
common_report:
  enabled: True
```
