### ISSUE TITLE
[ENH] Default configuration for study/dataset's de Novo gene sets 

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#298]
**Is your feature request related to a problem? Please describe.**
To enable a de Novo gene sets for a study/dataset you need to provide substantial configuration similar to the following:

```yaml
denovo_gene_sets:
  enabled: true
  selected_person_set_collections:
  - status

  standard_criterias:
    effect_types:
      segments:
        LGDs: LGDs
        Missense: missense
        Synonymous: synonymous
    sexes:
      segments:
        Female: F
        Male: M
        Unspecified: U
  recurrency_criteria:
    segments:
      Single:
        start: 1
        end: 2
      Triple:
        start: 3
        end: -1
      Recurrent:
        start: 2
        end: -1

  gene_sets_names:
  - LGDs
  - LGDs.Male
  - LGDs.Female
  - LGDs.Recurrent
  - LGDs.Single
  - LGDs.Triple

  - Missense
  - Missense.Male
  - Missense.Female
  - Missense.Recurrent
  - Missense.Single
  - Missense.Triple

  - Synonymous
  - Synonymous.Male
  - Synonymous.Female
  - Synonymous.Recurrent
  - Synonymous.Single
  - Synonymous.Triple
```

**Describe the solution you'd like**

We would like to have a default configuration for de Novo gene sets. So when somebody wants to enable de Novo gene sets, the configuration that should be provided should look like:

```yaml
denovo_gene_sets:
  enabled: true
```

**Additional context**

Make sure that the default configuration could be overwrite by study config.
