### ISSUE TITLE
[BUG] Genomic scores Cerberus schema does not define `chrom_mapping` field

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#304]
**What happened**:

The table section in the genomic scores resource configuration has a `chrom_mapping` subsection. 

**What you expected to happen**:

I expect that the `chrom_mapping` subsection in the table definition is allowed and well-defined in the Cerberus schema.

**Minimal Complete Verifiable Example**:

Example configuration of genomic score with `chrom_mapping` section is available in `hg38/scores/phyloP100way` score:

```yaml
type: position_score

table:
  filename: phyloP100way.bedGraph.gz
  format: tabix

  header_mode: none
  chrom_mapping:
    add_prefix: chr

  # defined by score_type
  chrom:
    index: 0
  pos_begin:
    index: 1
  pos_end:
    index: 2

# score values
scores:
    - id: phyloP100way
      type: float
      desc: "phyloP100way"
      index: 3

histograms:
  - score: phyloP100way
    bins: 100
    y_scale: "log"
    x_scale: "linear"

default_annotation:
  attributes:
    - source: phyloP100way
      destination: phylop100way

```

**Environment**:

- GPF version: development version 3.7dev from the master branch
