### ISSUE TITLE
[BUG] Cerberus schema for default annotation attributes in genomic scores is wrong

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#332]
**What happened**:

When you configure default annotation for a genomic score with the following configuration fragment:

```yaml
type: position_score

table:
  filename: whole_genome_SNVs.tsv.gz
  format: tabix

  # defined by score_type
  chrom:
    name: Chrom
  pos_begin:
    name: Pos

# score values
scores:
    - id: score1
      type: float
      name: score1
    
    - id: score2
      type: float
      name: score2

default_annotation:
  attributes:
    - score1
```

the validation of the score configuration does not pass. The culprit is the `default_annotation` section.

**What you expected to happen**:

The `default_annotation` section is processed by annotators. In the previous version of genomic scores, this section was not validated at all.

In the annotator classes, this section is first normalized and is validated after normalization. Its handling is here: https://github.com/iossifovlab/gpf/blob/54a5ddf65febae362fbac0081d71b42412dbe3f2/dae/dae/annotation/annotator_base.py#L16-L48

The idea is that during the normalization step, the above default annotation configuration snipped will be transformed into:

```
default_annotation:
  attributes:
  - source: score1
    destination: score1
```
that is valid.

Note that this behavior should be supported not only for genomic scores but for all genomic resources.

**Note**

We should consider if we want to fully validate genomic resources configuration or postpone the validation of some of its sections like the `default_annotation` and probably others.

Also, we need to have the same validation for `default_annotation` in all resources. It should not be defined in the genomic resources validation schema: https://github.com/iossifovlab/gpf/blob/54a5ddf65febae362fbac0081d71b42412dbe3f2/dae/dae/genomic_resources/genomic_scores.py#L470-L478
